-- Jalankan SEKALI di Supabase SQL Editor. Versi PERBAIKAN — 3 tabel
-- Matriks Perencanaan Aksi ProKlim (BAB V) ditaruh di halaman
-- PERENCANAAN (bukan Kelembagaan & Kebijakan seperti versi sebelumnya).
--
-- Aman dijalankan baik kamu SUDAH sempat menjalankan versi lama
-- (otomatis dipindah dari Kelembagaan ke Perencanaan) maupun BELUM
-- pernah menjalankannya sama sekali (otomatis dibuat baru).
--
-- Placeholder teks "Halaman ini sedang disiapkan..." di Perencanaan
-- juga dihapus karena sudah ada isi sungguhan.

delete from konten_halaman where kunci_blok = 'perencanaan-info';

insert into konten_halaman (halaman, kunci_blok, tipe_blok, judul_blok, urutan, konten)
values (
  'perencanaan', 'klb-matriks-aksi-adaptasi', 'tabel', 'Matriks Aksi Adaptasi', 1,
  '{"judul": "Matriks Aksi Adaptasi", "kolomPertamaTeks": true, "deskripsi": "Rencana aksi adaptasi ProKlim Desa Sanggang (BAB V.5.1 Perencanaan Aksi ProKlim).", "kolom": ["Ancaman", "Kegiatan", "Tujuan", "Indikator", "Tahapan Kegiatan", "Lokasi", "Waktu", "Kebutuhan", "Mitra Kerja", "Penanggung Jawab", "Prioritas"], "baris": [["Longsor pada lereng curam", "Tanaman penutup tanah pada garis kontur", "Menstabilkan lereng dan mengurangi erosi", "Minimal 500 bibit; 1 km garis kontur tertanam", "Musyawarah desa, identifikasi titik rawan, pembibitan/pengadaan, penentuan garis kontur, penyulaman, pemeliharaan, monev", "Lereng rawan, tebing jalan, talud", "2026–2030", "Bibit tanaman, ajir, cangkul, pupuk kandang, alat ukur kontur, tenaga kerja", "BPBD, Dinas Pertanian, perguruan tinggi", "Ketua Tim ProKlim dan bidang adaptasi", "1"], ["Longsor dan degradasi lereng", "Agroforestri lereng (alpukat, durian, nangka, petai, kaliandra)", "Menambah tutupan permanen dan pendapatan", "3.000 bibit; minimal 15 ha", "Pemetaan lahan, persetujuan pemilik, pengadaan bibit, pelatihan tanam, penanaman, mulsa, pemeliharaan, evaluasi", "Kebun warga dan perbukitan", "2027–2028", "Bibit, pupuk organik, mulsa, alat tanam, pagar tanaman sederhana", "Dinas Pertanian, KWT, kelompok tani", "Ketua kelompok tani/kebun", "1"], ["Kekeringan domestik dan pertanian", "Perlindungan mata air dan penghijauan sempadan", "Menjaga ketersediaan air desa", "1 titik sumber air ditata; 50 pohon pelindung", "Identifikasi titik air, desain teknis, pembibitan tanaman, penanaman, pemeliharaan, pencatatan debit sederhana", "Mata air dan sungai", "2027–2028", "Bibit pohon, alat gali, papan larangan", "Pemdes, BPBD, PUPR, warga", "Bidang adaptasi dan RT/RW", "1"], ["Kekeringan pangan rumah tangga", "Pekarangan tahan iklim", "Menjaga pangan keluarga dan diversifikasi pendapatan", "200 rumah tangga; 1 paket pekarangan per RT", "Sosialisasi, demplot, pembagian bibit, pelatihan mulsa-penyiraman hemat, pendampingan", "Pekarangan seluruh RW", "2027–2030", "Bibit cabai, kelor, pisang, pepaya, empon, tangki air/drum sederhana, mulsa", "PKK, KWT, penyuluh", "Ketua PKK dan bidang adaptasi", "2"], ["Longsor dan limpasan hujan", "Rehabilitasi tebing jalan dengan vegetasi dan drainase mikro", "Mengurangi gerusan dan gangguan akses", "1 titik tebing/jalan kritis tertangani", "Inventarisasi titik, desain sederhana, pembersihan, penanaman, drainase mikro, pemeliharaan, pemeriksaan pascahujan", "Koridor jalan dan talud kritis", "2029", "Bibit tanaman, batu lokal bila perlu, tenaga gotong royong", "Pemdes, BPBD, warga", "Pemerintah desa dan bidang adaptasi", "2"]]}'::jsonb
)
on conflict (kunci_blok) do update set halaman = excluded.halaman, urutan = excluded.urutan, judul_blok = excluded.judul_blok, konten = excluded.konten;

insert into konten_halaman (halaman, kunci_blok, tipe_blok, judul_blok, urutan, konten)
values (
  'perencanaan', 'klb-matriks-aksi-mitigasi', 'tabel', 'Matriks Aksi Mitigasi', 2,
  '{"judul": "Matriks Aksi Mitigasi", "kolomPertamaTeks": true, "deskripsi": "Rencana aksi mitigasi ProKlim Desa Sanggang (BAB V.5.2 Perencanaan Aksi ProKlim).", "kolom": ["Potensi Mitigasi", "Kegiatan", "Tujuan", "Indikator", "Tahapan Kegiatan", "Lokasi", "Waktu", "Kebutuhan", "Mitra Kerja", "Penanggung Jawab", "Prioritas"], "baris": [["Kebun campuran, lahan palawija, pekarangan, dan kultur bertani/perkebunan yang kuat", "Peningkatan tutupan lahan dengan pohon tahunan", "Menambah biomassa dan serapan karbon", "1.000 pohon tertanam", "Musyawarah, penetapan lokasi, pembibitan, distribusi bibit, tanam, penyulaman", "Kebun, pekarangan, fasilitas umum", "2028, 2030", "Bibit pohon buah dan pelindung, pupuk organik, ajir, formulir pendataan", "BPDAS, CDK XI, DLH, Dinas Pertanian", "Bidang mitigasi", "1"], ["Serapan GRK dan adaptasi lereng", "Koridor hijau desa di jalan, tebing, tanah kas/fasos", "Menambah vegetasi permanen dan peneduh", "500 pohon/semak produktif", "Pemetaan, persetujuan lokasi, penanaman, pemeliharaan, penyulaman", "Bahu jalan, fasos/fasum", "2028, 2030", "Bibit, tenaga gotong royong, air siram awal", "Pemdes, RT/RW", "Kepala desa/bidang mitigasi", "1"], ["Reduksi emisi dari biomassa dan limbah organik", "Kompos dan biogas dari residu kebun/sampah organik/kotoran ternak", "Mengurangi pembakaran terbuka dan memperbaiki tanah", "2 kompos komunal; 1 IPAL biogas ternak", "Sosialisasi, pelatihan, penyediaan sarana prasarana, produksi kompos dan biogas, pemanfaatan hasil", "RW prioritas dan kelompok ternak", "2026–2030", "Drum/komposter, sekam, aktivator, alat angkut, biodigester", "DLH, PKK, kelompok tani/ternak, BUMDesa", "Bidang mitigasi dan PKK", "1"], ["Reduksi emisi tak langsung dan perlindungan serapan", "Himbauan larangan pembakaran terbuka dan perlindungan vegetasi", "Mencegah degradasi dan menjaga vegetasi", "SK/peraturan internal; papan informasi", "Penyusunan draft, musyawarah, penetapan, sosialisasi, pengawasan warga", "Seluruh desa, titik rawan", "2027", "Draft aturan, baliho/papan, forum sosialisasi", "BPD, Pemdes, RT/RW", "Kepala desa", "2"]]}'::jsonb
)
on conflict (kunci_blok) do update set halaman = excluded.halaman, urutan = excluded.urutan, judul_blok = excluded.judul_blok, konten = excluded.konten;

insert into konten_halaman (halaman, kunci_blok, tipe_blok, judul_blok, urutan, konten)
values (
  'perencanaan', 'klb-matriks-penguatan-kelembagaan', 'tabel', 'Matriks Penguatan Kelembagaan', 3,
  '{"judul": "Matriks Penguatan Kelembagaan", "kolomPertamaTeks": true, "deskripsi": "Rencana penguatan kelembagaan ProKlim Desa Sanggang (BAB V.5.3 Perencanaan Aksi ProKlim). Kolom \"Penanggung Jawab Pelaksana\" dan \"Penanggung Jawab Akhir\" mengikuti dokumen sumber yang memuat dua peran penanggung jawab berbeda.", "kolom": ["Kegiatan", "Tujuan", "Indikator", "Penanggung Jawab Pelaksana", "Waktu", "Kebutuhan", "Mitra Kerja", "Penanggung Jawab Akhir", "Prioritas"], "baris": [["Pergantian kepengurusan Tim Pelaksana ProKlim melalui SK Kepala Desa", "Dasar legal, peran, dan alur kerja jelas", "SK tim terbit; tupoksi disepakati", "Bidang mitigasi", "2026", "Dokumen SK, rapat, administrasi", "Pemerintah desa, BPD, kecamatan", "Kepala desa", "1"], ["Pelatihan pembibitan dan konservasi tanah-air", "Meningkatkan kapasitas teknis masyarakat", "50 peserta terlatih; 1 materi pelatihan desa", "Kepala desa/bidang mitigasi", "2027", "Narasumber, konsumsi, alat praktik, bahan tanam", "BPBD, Dinas Pertanian, DLH, perguruan tinggi", "Ketua Tim ProKlim", "1"], ["Forum kemitraan berkala untuk longsor, kekeringan, dan penghijauan", "Menjamin dukungan teknis dan pendanaan", "Minimal 1 rapat koordinasi/tahun", "Bidang mitigasi dan PKK", "2026–2030", "Ruang rapat dan administrasi", "BPBD, dinas teknis, PMI/PDAM, perguruan tinggi, dunia usaha", "Koordinator kemitraan", "2"], ["Gotong royong pemeliharaan tanaman per RT/RW", "Menjaga tingkat hidup bibit dan rasa memiliki", "Jadwal pemeliharaan per RT/RW", "Kepala desa", "2026–2030", "Buku kontrol, alat siram, perlengkapan ringan", "RT/RW, PKK, karang taruna", "RT/RW dan koordinator adaptasi-mitigasi", "1"]]}'::jsonb
)
on conflict (kunci_blok) do update set halaman = excluded.halaman, urutan = excluded.urutan, judul_blok = excluded.judul_blok, konten = excluded.konten;
